#!/usr/bin/node
const args = process.argv;

function stripSame (n, arr) {
	for (let i = 0; i < arr.length; i++) {
		num = parseInt(arr[i]);
		if (n === num) {
			arr.splice(indexOf(num), 1);
		}
	}
	return arr;
}

function isZero (arr) {
	if (arr.length <= 3)
	{
		return true;
	} else {
		return false;
	}
}

function getMax (arr) {
	let max = arr[0];
	for (let i = 0; i < arr.length; i++) {
		if (arr[i] > max) max = arr[i];
	}
	return max;
} 

for (let k = 0; k <
